# Generated by Django 2.1 on 2019-09-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20190924_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='latitutde',
            new_name='latitude',
        ),
    ]
