# Generated by Django 2.1 on 2019-09-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20190926_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='category',
        ),
        migrations.RemoveField(
            model_name='site',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='site',
            name='region',
        ),
        migrations.RemoveField(
            model_name='site',
            name='states',
        ),
    ]
